spring:
  profiles: language-pack-cn
language-pack-cn:
  packName: "简体中文"
  packShortName: CN
  landing_storeName: "商店"
  landing_table: "座号"
  landing_orderNow: "开始下单"
  landing_poweredBy: "Powered By"
  item_detail_comboPrice: "组合价格"
  item_detail_alacartePrice: "单点价格"
  item_detail_totalPrice: "总价"
  item_detail_select: "选择"
  item_detail_addToCart: "添加到购物车"
  tier_selection_selection: "选项"
  tier_selection_itemRemaining: "剩余选择"
  tier_selection_done: "完成"
  
  dialog_cart_add_success_title: "商品已成功添加到购物车！"
  dialog_button_ok: "确定"