spring:
  profiles:
    active:
    - development-data
    - application-data
    - language-pack-en
    - language-pack-cn
    - error-data
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        show_sql: true

---

spring:
  profiles: development-data
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=tenant
    username: sa
    password: MPay@1234
    
upload-path: byod-img/
get-upload-path: /byod-img/
menu-path: byod-menu/
get-menu-path: /byod-menu/
log-path: logger
byod-cloud-url: 172.31.99.77:8080

db-port: 1433
db-domain: localhost
db-username: sa
db-password: MPay@1234
db-driver: com.microsoft.sqlserver.jdbc.SQLServerDriver

---

spring:
  profiles: production-data
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=tenant
    username: sa
    password: MPay@1234
    
---

spring:
  profiles: application-data
application-data:
  appName: "KFC"
  mainLogoPath: "/assets/images/order/logo/main_logo.png"
  shortcutLogoPath: "/assets/images/order/logo/shortcut_logo.png"
  mainBackgroundPath: "/assets/images/order/background/main_background.png"
  landingLogoPath: "/assets/images/order/logo/shortcut_logo.png"
  mainColor: "#C41230"
  subColor: "#000000"
  mainTextColor: "#FFFFFF"
  subTextColor: "#FFFFFF"
  localeButtonColor: "#FFFFFF"
  mainButtonTextColor: "#FFFFFF"
  mainButtonBackgroundColor: "#C41230"
  mainButtonBackgroundHoverColor: "#C41230"
  mainButtonBackgroundFocusColor: "#C41230"