spring:
  profiles:
    active:
    - development-data
    - application-data
    - language-pack-en
    - language-pack-cn
    - error-data
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        show_sql: true

---

spring:
  profiles: development-data
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tenant?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234

access-drive: C
upload-path: byod-img/
get-upload-path: /byod-img/
menu-path: byod-menu/
get-menu-path: /byod-menu/
log-path: logger
pdf-path: pdf-folder/
byod-cloud-url: http://localhost:8081

 
server:
  port: 8081
---

spring:
  profiles: uat-data
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.79.42:3306/tenant?useTimezone=true&serverTimezone=UTC
    username: root
    password: MPay@USJ21

access-drive: C
upload-path: /opt/tomcat/apache-tomcat-8.5.45/webapps/byod/byod-img/
get-upload-path: /byod-img/
menu-path: /opt/tomcat/apache-tomcat-8.5.45/webapps/byod/byod-menu/
get-menu-path: /byod-menu/
log-path: /opt/tomcat/apache-tomcat-8.5.45/webapps/byod/logger/
pdf-path: /opt/tomcat/apache-tomcat-8.5.45/webapps/byod/pdf-folder/
byod-cloud-url: http://192.168.79.41:8080/byod

---

spring:
  profiles: production-data
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=tenant
    username: sa
    password: MPay@1234
    
access-drive: C
upload-path: byod-img/
get-upload-path: /byod-img/
menu-path: byod-menu/
get-menu-path: /byod-menu/
log-path: logger
pdf-path: pdf-folder/
byod-cloud-url: http://localhost:8080
    
---

spring:
  profiles: application-data
application-data:
  appName: "KFC"
  mainLogoPath: "/assets/images/order/logo/main_logo.png"
  shortcutLogoPath: "/assets/images/order/logo/shortcut_logo.png"
  mainBackgroundPath: "/assets/images/order/background/main_background.png"
  landingLogoPath: "/assets/images/order/logo/shortcut_logo.png"
  mainColor: "#C41230"
  subColor: "#000000"
  mainTextColor: "#FFFFFF"
  subTextColor: "#FFFFFF"
  localeButtonColor: "#FFFFFF"
  mainButtonTextColor: "#FFFFFF"
  mainButtonBackgroundColor: "#C41230"
  mainButtonBackgroundHoverColor: "#C41230"
  mainButtonBackgroundFocusColor: "#C41230"
  