spring:
  profiles: language-pack-cn
language-pack-cn:
  packName: "简体中文"
  packShortName: CN
  landing_storeName: "商店"
  landing_table: "座号"
  landing_orderNow: "开始下单"
  landing_poweredBy: "Powered By"
  item_detail_comboPrice: "组合价格"
  item_detail_alacartePrice: "单点价格"
  item_detail_totalPrice: "总价"
  item_detail_select: "选择"
  item_detail_addToCart: "添加到购物车"
  item_detail_quantity: "数量"
  tier_selection_selection: "选项"
  tier_selection_itemRemaining: "剩余选择"
  tier_selection_done: "完成"
  cart_empty_message: "购物车是空的。 请开始下单。"
  cart_summary: "购物车汇总"
  cart_total: "总计"
  cart_subtotal: "小计"
  cart_send_order: "发送订单"
  cart_checkout: "结账"
  edit_item_detail_editCart: "修改购物车"
  
  dialog_cart_add_success_title: "商品已成功添加到购物车！"
  dialog_cart_edit_success_title: "商品已成功被修改！"
  dialog_reset_cart_title: "您确定要返回主页而清除购物车吗？"
  dialog_delete_cart_item_title: "您确定要从购物车中删除该商品吗？"
  dialog_send_order_success_title: "订单创建成功!"
  dialog_send_order_failed_title: "订单无法创建!"
  dialog_button_ok: "确定"
  dialog_button_yes: "是的"
  dialog_button_no: "不是"