spring:
  profiles: language-pack-en
language-pack-en:
  packName: "English"
  packShortName: EN
  landing_storeName: "Store Name"
  landing_table: "Table"
  landing_orderNow: "Order Now"
  landing_poweredBy: "Powered By"
  item_detail_comboPrice: "Combo Price"
  item_detail_alacartePrice: "A la carte Price"
  item_detail_totalPrice: "Total Price"
  item_detail_select: "Select"
  item_detail_addToCart: "Add to Cart"
  tier_selection_selection: "Selection"
  tier_selection_itemRemaining: "Item(s) Remaining"
  tier_selection_done: "Done"
  
  dialog_cart_add_success_title: "Item Added to Cart Successfully!"
  dialog_button_ok: "OK"