spring:
  profiles: language-pack-en
language-pack-en:
  packName: "English"
  packShortName: EN
  landing_storeName: "Store Name"
  landing_table: "Table"
  landing_orderNow: "Order Now"
  landing_poweredBy: "Powered By"
  item_detail_comboPrice: "Combo Price"
  item_detail_alacartePrice: "A la carte Price"
  item_detail_totalPrice: "Total Price"
  item_detail_select: "Select"
  item_detail_addToCart: "Add to Cart"
  item_detail_quantity: "Quantity"
  tier_selection_selection: "Selection"
  tier_selection_itemRemaining: "Item(s) Remaining"
  tier_selection_done: "Done"
  cart_empty_message: "The cart is empty. Please proceed to order."
  cart_summary: "Cart Summary"
  cart_total: "Total"
  cart_subtotal: "Subtotal"
  cart_checkout: "Checkout"
  
  dialog_cart_add_success_title: "Item Added to Cart Successfully!"
  dialog_reset_cart_title: "Are you sure you want to clear your cart by returning to main page?"
  dialog_button_ok: "OK"
  dialog_button_yes: "Yes"
  dialog_button_no: "No"